/**
 * @file 百分比常量
 * @author Joker.X
 */

/**
 * 0% 百分比
 */
export const P0: string = "0%";

/**
 * 5% 百分比
 */
export const P5: string = "5%";

/**
 * 10% 百分比
 */
export const P10: string = "10%";

/**
 * 15% 百分比
 */
export const P15: string = "15%";

/**
 * 20% 百分比
 */
export const P20: string = "20%";

/**
 * 25% 百分比
 */
export const P25: string = "25%";

/**
 * 30% 百分比
 */
export const P30: string = "30%";

/**
 * 35% 百分比
 */
export const P35: string = "35%";

/**
 * 40% 百分比
 */
export const P40: string = "40%";

/**
 * 45% 百分比
 */
export const P45: string = "45%";

/**
 * 50% 百分比
 */
export const P50: string = "50%";

/**
 * 55% 百分比
 */
export const P55: string = "55%";

/**
 * 60% 百分比
 */
export const P60: string = "60%";

/**
 * 65% 百分比
 */
export const P65: string = "65%";

/**
 * 70% 百分比
 */
export const P70: string = "70%";

/**
 * 75% 百分比
 */
export const P75: string = "75%";

/**
 * 80% 百分比
 */
export const P80: string = "80%";

/**
 * 85% 百分比
 */
export const P85: string = "85%";

/**
 * 90% 百分比
 */
export const P90: string = "90%";

/**
 * 95% 百分比
 */
export const P95: string = "95%";

/**
 * 100% 百分比
 */
export const P100: string = "100%";
