export const MAIN_CARD: string = 'Network Demo';
export const NETWORK_PAGE_TITLE: string = 'Base Network 示例';
export const TEST_RESULT_TITLE: string = 'UITest 回传标题';
export const TEST_RESULT_DESC: string = 'UITest 回传说明';
export const MOCK_GOODS_TITLE: string = 'Mock 商品标题';
export const MOCK_GOODS_SUB_TITLE: string = 'Mock 商品副标题';
export const LOADING_TEXT: string = '加载中...';
export const START_TIMEOUT: number = 8000;
